[package]
name = "svc-nats-client"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/foxford/svc-nats-client"
description = "Async nats client"

[dependencies]
anyhow = "1.0"
async-nats = "0.29"
async-trait = "0.1"
futures = "0.3"
serde = "1.0"
svc-agent = "0.19"
thiserror = "1.0"
tracing = "0.1"
uuid = { version = "0.8", features = ["serde"] }
