[package]
name = "svc-nats-client"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/foxford/svc-nats-client"
description = "Async nats client"

[dependencies]
anyhow = "1"
async-nats = "0.27"
async-trait = "0.1"
tracing = "0.1"
