[package]
name = "svc-nats-client"
version = "0.2.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/foxford/svc-nats-client"
description = "Async nats client"

[dependencies]
anyhow = "1.0"
async-nats = "0.29"
async-trait = "0.1"
futures = "0.3"
humantime-serde = "1"
reqwest = "0.11"
serde = "1.0"
svc-agent = "0.20"
svc-error = { version = "0.5", features = ["sentry-extension"] }
thiserror = "1.0"
tracing = "0.1"
uuid = { version = "1.3", features = ["serde"] }
